package com.entities;
// Generated 4 avr. 2018 15:24:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ddate generated by hbm2java
 */
//@Entity
@Entity
//@Table(name = "ddate", catalog = "tests")
public class Ddate implements java.io.Serializable {

	private Date dday;
	private Boolean offday;

	public Ddate() {
	}

	public Ddate(Date dday) {
		this.dday = dday;
	}

	public Ddate(Date dday, Boolean offday) {
		this.dday = dday;
		this.offday = offday;
	}

	@Id
	
	//@Temporal(TemporalType.DATE)
	@Column(name = "dday", unique = true, nullable = false, length = 10)
	public Date getDday() {
		return this.dday;
	}

	public void setDday(Date dday) {
		this.dday = dday;
	}

	@Column(name = "offday")
	public Boolean getOffday() {
		return this.offday;
	}

	public void setOffday(Boolean offday) {
		this.offday = offday;
	}

}
